version: '3.8'

services:
  app:
    build:
      context: .
    container_name: laravel-app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      APP_KEY: ${APP_KEY}
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: sezindb
      DB_USERNAME: root
      DB_PASSWORD: ""
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: laravel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: sezindb
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  artisan:
    image: composer:latest
    container_name: artisan-container
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["php", "artisan"]

volumes:
  mysql-data:
